# Generated by Django 5.2.4 on 2025-07-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(choices=[('high_volume', 'High request volume'), ('sensitive_path', 'Accessed sensitive paths'), ('multiple_reasons', 'Multiple suspicious activities')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
